source "https://rubygems.org"

gem "rake"
gem "jazzy"
gem "cocoapods", "1.8.1"
gem "colorize", "~> 0.8.1"
gem "danger", "~> 6.0"
gem "danger-swiftformat", "~> 0.6.0"
gem "danger-swiftlint", "~> 0.23.0"
gem "redcarpet", "~> 3.5.0"
