source "https://rubygems.org"

gem "rake"
gem "jazzy"
gem "cocoapods", "1.7.5"
gem "colorize", "~> 0.8.1"
gem "danger", "~> 6.0"
gem "danger-swiftformat", "~> 0.5.0"
gem "danger-swiftlint", "~> 0.22.0"
gem "redcarpet", "~> 3.4.0"
