#!/usr/bin/env bash
# mise description="Build on Linux"

podman run --rm --interactive --tty --volume "$(pwd):/package" --workdir "/package" swift:5.10.1 bash -c "swift build --configuration release"
