#if !canImport(ObjectiveC)
import XCTest

extension AEXML_XcodeFormatTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AEXML_XcodeFormatTests = [
        ("test_BuildAction_attributes_sorted_when_original_sorted", test_BuildAction_attributes_sorted_when_original_sorted),
        ("test_BuildAction_attributes_sorted_when_original_unsorted", test_BuildAction_attributes_sorted_when_original_unsorted),
    ]
}

extension Array_PlistValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Array_PlistValueTests = [
        ("test_arrayPlistValue_returnsTheCorrectValue", test_arrayPlistValue_returnsTheCorrectValue),
    ]
}

extension BuildPhaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BuildPhaseTests = [
        ("test_carbonResources_hasTheCorrectBuildPhase", test_carbonResources_hasTheCorrectBuildPhase),
        ("test_carbonResources_hasTheCorrectRawValue", test_carbonResources_hasTheCorrectRawValue),
        ("test_copyFiles_hasTheCorrectBuildPhase", test_copyFiles_hasTheCorrectBuildPhase),
        ("test_copyFiles_hasTheCorrectRawValue", test_copyFiles_hasTheCorrectRawValue),
        ("test_frameworks_hasTheCorrectBuildPhase", test_frameworks_hasTheCorrectBuildPhase),
        ("test_frameworks_hasTheCorrectRawValue", test_frameworks_hasTheCorrectRawValue),
        ("test_headers_hasTheCorrectBuildPhase", test_headers_hasTheCorrectBuildPhase),
        ("test_headers_hasTheCorrectRawValue", test_headers_hasTheCorrectRawValue),
        ("test_resources_hasTheCorrectBuildPhase", test_resources_hasTheCorrectBuildPhase),
        ("test_resources_hasTheCorrectRawValue", test_resources_hasTheCorrectRawValue),
        ("test_runStript_hasTheCorrectBuildPhase", test_runStript_hasTheCorrectBuildPhase),
        ("test_runStript_hasTheCorrectRawValue", test_runStript_hasTheCorrectRawValue),
        ("test_sources_hasTheCorrectBuildPhase", test_sources_hasTheCorrectBuildPhase),
        ("test_sources_hasTheCorrectRawValue", test_sources_hasTheCorrectRawValue),
    ]
}

extension BuildSettingProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BuildSettingProviderTests = [
        ("test_targetSettings_iosAplication", test_targetSettings_iosAplication),
        ("test_targetSettings_iosExtension", test_targetSettings_iosExtension),
        ("test_targetSettings_iosFramework", test_targetSettings_iosFramework),
        ("test_targetSettings_iOSUITests", test_targetSettings_iOSUITests),
        ("test_targetSettings_iOSUnitTests", test_targetSettings_iOSUnitTests),
        ("test_targetSettings_macOSAplication", test_targetSettings_macOSAplication),
        ("test_targetSettings_macOSUnitTests", test_targetSettings_macOSUnitTests),
        ("test_targetSettings_tvOSAplication", test_targetSettings_tvOSAplication),
        ("test_targetSettings_tvOSUnitTests", test_targetSettings_tvOSUnitTests),
        ("test_targetSettings_watchOSAplication", test_targetSettings_watchOSAplication),
    ]
}

extension CommentedStringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommentedStringTests = [
        ("test_commentedStringEscaping", test_commentedStringEscaping),
    ]
}

extension DictionaryExtrasTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DictionaryExtrasTests = [
        ("test_loadPlist_returnsANilValue_whenTheFileDoesntExist", test_loadPlist_returnsANilValue_whenTheFileDoesntExist),
        ("test_loadPlist_returnsTheDictionary_whenTheFileDoesExist", test_loadPlist_returnsTheDictionary_whenTheFileDoesExist),
    ]
}

extension Dictionary_PlistValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Dictionary_PlistValueTests = [
        ("test_dictionaryPlistValue_returnsTheCorrectValue", test_dictionaryPlistValue_returnsTheCorrectValue),
    ]
}

extension ObjectReferenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ObjectReferenceTests = [
        ("test_reference_cachesObject", test_reference_cachesObject),
        ("test_reference_changesTemporary", test_reference_changesTemporary),
        ("test_reference_fetches", test_reference_fetches),
        ("test_reference_fixesValue", test_reference_fixesValue),
        ("test_reference_generation_changesPerObject", test_reference_generation_changesPerObject),
        ("test_reference_generation_doesntChangeFixed", test_reference_generation_doesntChangeFixed),
        ("test_reference_generation_handlesMultipleDuplicates", test_reference_generation_handlesMultipleDuplicates),
        ("test_reference_generation_prefixed_duplicateHasSuffix", test_reference_generation_prefixed_duplicateHasSuffix),
        ("test_reference_generation_prefixed_includesAcronym", test_reference_generation_prefixed_includesAcronym),
        ("test_reference_generation_prefixed_isDeterministic", test_reference_generation_prefixed_isDeterministic),
        ("test_reference_generation_usesIdentifier", test_reference_generation_usesIdentifier),
        ("test_reference_generation_xcode_duplicatesHave24Characters", test_reference_generation_xcode_duplicatesHave24Characters),
        ("test_reference_generation_xcode_duplicatesHaveOnlyAlphaNumerics", test_reference_generation_xcode_duplicatesHaveOnlyAlphaNumerics),
        ("test_reference_generation_xcode_isDeterministic", test_reference_generation_xcode_isDeterministic),
        ("test_reference_generation_xcode_nonTempHas24Characters", test_reference_generation_xcode_nonTempHas24Characters),
        ("test_reference_handleReferenceChange", test_reference_handleReferenceChange),
        ("test_reference_nonTempHasOnlyAlphaNumerics", test_reference_nonTempHasOnlyAlphaNumerics),
        ("test_reference_tempHasPrefix", test_reference_tempHasPrefix),
    ]
}

extension PBXAggregateTargetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXAggregateTargetTests = [
        ("test_init_failsWhenNameIsMissing", test_init_failsWhenNameIsMissing),
        ("test_isa_returnsTheCorrectValue", test_isa_returnsTheCorrectValue),
    ]
}

extension PBXBatchUpdaterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXBatchUpdaterTests = [
        ("test_addFile_alreadyExisted", test_addFile_alreadyExisted),
        ("test_addFile_alreadyExistedWithSubgroups", test_addFile_alreadyExistedWithSubgroups),
        ("test_addFile_byFileName", test_addFile_byFileName),
        ("test_addFile_useMainProjectGroup", test_addFile_useMainProjectGroup),
        ("test_addFile_withSubgroups", test_addFile_withSubgroups),
    ]
}

extension PBXBuildFileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXBuildFileTests = [
        ("test_isa_returnsTheCorrectValue", test_isa_returnsTheCorrectValue),
    ]
}

extension PBXBuildPhaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXBuildPhaseTests = [
        ("test_add_files_only_once", test_add_files_only_once),
        ("test_add_files", test_add_files),
    ]
}

extension PBXBuildRuleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXBuildRuleTests = [
        ("test_equal_shouldReturnTheCorrectValue", test_equal_shouldReturnTheCorrectValue),
        ("test_init_initializesTheBuildRuleWithTheRightAttributes", test_init_initializesTheBuildRuleWithTheRightAttributes),
        ("test_isa_returnsTheCorrectValue", test_isa_returnsTheCorrectValue),
    ]
}

extension PBXContainerItemProxyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXContainerItemProxyTests = [
        ("test_init_shouldFail_ifContainerPortalIsMissing", test_init_shouldFail_ifContainerPortalIsMissing),
        ("test_itHasTheCorrectIsa", test_itHasTheCorrectIsa),
        ("test_maintains_remoteID", test_maintains_remoteID),
    ]
}

extension PBXCopyFilesBuildPhaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXCopyFilesBuildPhaseTests = [
        ("test_init_fails_whenBuildActionMaskIsMissing", test_init_fails_whenBuildActionMaskIsMissing),
        ("test_init_fails_whenDstPathIsMissing", test_init_fails_whenDstPathIsMissing),
        ("test_init_fails_whenDstSubfolderSpecIsMissing", test_init_fails_whenDstSubfolderSpecIsMissing),
        ("test_init_fails_whenFilesIsMissing", test_init_fails_whenFilesIsMissing),
        ("test_init_fails_whenRunOnlyForDeploymentPostprocessingIsMissing", test_init_fails_whenRunOnlyForDeploymentPostprocessingIsMissing),
        ("test_isa_returnsTheRightValue", test_isa_returnsTheRightValue),
        ("test_subFolder_executables_hasTheCorrectValue", test_subFolder_executables_hasTheCorrectValue),
        ("test_subFolder_frameworks_hasTheCorrectValue", test_subFolder_frameworks_hasTheCorrectValue),
        ("test_subFolder_javaResources_hasTheCorrectValue", test_subFolder_javaResources_hasTheCorrectValue),
        ("test_subFolder_Path_hasTheCorrectValue", test_subFolder_Path_hasTheCorrectValue),
        ("test_subFolder_plugins_hasTheCorrectValue", test_subFolder_plugins_hasTheCorrectValue),
        ("test_subFolder_producsDirectory_hasTheCorrectValue", test_subFolder_producsDirectory_hasTheCorrectValue),
        ("test_subFolder_resources_hasTheCorrectValue", test_subFolder_resources_hasTheCorrectValue),
        ("test_subFolder_sharedFrameworks_hasTheCorrectValue", test_subFolder_sharedFrameworks_hasTheCorrectValue),
        ("test_subFolder_sharedSupport_hasTheCorrectValue", test_subFolder_sharedSupport_hasTheCorrectValue),
        ("test_subFolder_wrapper_hasTheCorrectValue", test_subFolder_wrapper_hasTheCorrectValue),
    ]
}

extension PBXFileElementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXFileElementTests = [
        ("test_equal_returnsTheCorrectValue", test_equal_returnsTheCorrectValue),
        ("test_fullPath_with_nested_groups", test_fullPath_with_nested_groups),
        ("test_fullPath_with_parent", test_fullPath_with_parent),
        ("test_fullPath_without_parent", test_fullPath_without_parent),
        ("test_init_initializesTheFileElementWithTheRightAttributes", test_init_initializesTheFileElementWithTheRightAttributes),
        ("test_isa_returnsTheCorrectValue", test_isa_returnsTheCorrectValue),
        ("test_plistKeyAndValue_returns_dictionary_value", test_plistKeyAndValue_returns_dictionary_value),
    ]
}

extension PBXFileReferenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXFileReferenceTests = [
        ("test_equal_returnsTheCorrectValue", test_equal_returnsTheCorrectValue),
        ("test_init_initializesTheReferenceWithTheRightAttributes", test_init_initializesTheReferenceWithTheRightAttributes),
        ("test_isa_hashTheCorrectValue", test_isa_hashTheCorrectValue),
    ]
}

extension PBXFrameworksBuildPhaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXFrameworksBuildPhaseTests = [
        ("test_init_fails_whenTheFilesAreMissing", test_init_fails_whenTheFilesAreMissing),
        ("test_isa_returnsTheRightValue", test_isa_returnsTheRightValue),
    ]
}

extension PBXGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXGroupTests = [
        ("test_addFile_assignParent", test_addFile_assignParent),
        ("test_addFileWithDeveloperDirSourceTreePath_pathIsTheSameAsAdded", test_addFileWithDeveloperDirSourceTreePath_pathIsTheSameAsAdded),
        ("test_addFileWithSDKRootSourceTreePath_pathIsTheSameAsAdded", test_addFileWithSDKRootSourceTreePath_pathIsTheSameAsAdded),
        ("test_addGroup_assignParent", test_addGroup_assignParent),
        ("test_addNotExistingFileValidatinPresence_assignsParent", test_addNotExistingFileValidatinPresence_assignsParent),
        ("test_addNotExistingFileWithoutValidatinPresence_throws", test_addNotExistingFileWithoutValidatinPresence_throws),
        ("test_addVariantGroup", test_addVariantGroup),
        ("test_createGroupWithFile_assignParent", test_createGroupWithFile_assignParent),
        ("test_isa_returnsTheCorrectValue", test_isa_returnsTheCorrectValue),
    ]
}

extension PBXHeadersBuildPhaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXHeadersBuildPhaseTests = [
        ("test_init_failsWhenRunOnlyForDeploymentPostProcessingIsMissing", test_init_failsWhenRunOnlyForDeploymentPostProcessingIsMissing),
        ("test_init_failsWhenTheBuildActionMaskIsMissing", test_init_failsWhenTheBuildActionMaskIsMissing),
        ("test_init_failWhenFilesIsMissing", test_init_failWhenFilesIsMissing),
        ("test_isa_returnsTheCorrectValue", test_isa_returnsTheCorrectValue),
    ]
}

extension PBXNativeTargetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXNativeTargetTests = [
        ("test_addDependency", test_addDependency),
        ("test_init_failsWhenNameIsMissing", test_init_failsWhenNameIsMissing),
        ("test_isa_returnsTheCorrectValue", test_isa_returnsTheCorrectValue),
    ]
}

extension PBXOutputSettingsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXOutputSettingsTests = [
        ("test_PBXBuildPhaseFileOrder_by_filename", test_PBXBuildPhaseFileOrder_by_filename),
        ("test_PBXBuildPhaseFileOrder_unsorted", test_PBXBuildPhaseFileOrder_unsorted),
        ("test_PBXFileOrder_Other_by_filename", test_PBXFileOrder_Other_by_filename),
        ("test_PBXFileOrder_Other_by_uuid", test_PBXFileOrder_Other_by_uuid),
        ("test_PBXFileOrder_PBXBuildFile_by_filename", test_PBXFileOrder_PBXBuildFile_by_filename),
        ("test_PBXFileOrder_PBXBuildFile_by_filename_when_nil_name_and_path", test_PBXFileOrder_PBXBuildFile_by_filename_when_nil_name_and_path),
        ("test_PBXFileOrder_PBXBuildFile_by_filename_when_no_file", test_PBXFileOrder_PBXBuildFile_by_filename_when_no_file),
        ("test_PBXFileOrder_PBXBuildFile_by_uuid", test_PBXFileOrder_PBXBuildFile_by_uuid),
        ("test_PBXFileOrder_PBXBuildPhaseFile_by_filename", test_PBXFileOrder_PBXBuildPhaseFile_by_filename),
        ("test_PBXFileOrder_PBXBuildPhaseFile_by_uuid", test_PBXFileOrder_PBXBuildPhaseFile_by_uuid),
        ("test_PBXFileOrder_PBXFileReference_by_filename", test_PBXFileOrder_PBXFileReference_by_filename),
        ("test_PBXFileOrder_PBXFileReference_by_filename_when_nil_name_and_path", test_PBXFileOrder_PBXFileReference_by_filename_when_nil_name_and_path),
        ("test_PBXFileOrder_PBXFileReference_by_uuid", test_PBXFileOrder_PBXFileReference_by_uuid),
        ("test_PBXNavigatorFileOrder_by_filename", test_PBXNavigatorFileOrder_by_filename),
        ("test_PBXNavigatorFileOrder_by_filename_groups_first", test_PBXNavigatorFileOrder_by_filename_groups_first),
        ("test_PBXNavigatorFileOrder_unsorted", test_PBXNavigatorFileOrder_unsorted),
    ]
}

extension PBXProductTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXProductTypeTests = [
        ("test_appExtension_hasTheRightValue", test_appExtension_hasTheRightValue),
        ("test_application_hasTheRightValue", test_application_hasTheRightValue),
        ("test_bundle_hasTheRightValue", test_bundle_hasTheRightValue),
        ("test_commandLineTool_hasTheRightValue", test_commandLineTool_hasTheRightValue),
        ("test_dynamicLibrary_hasTheRightValue", test_dynamicLibrary_hasTheRightValue),
        ("test_framework_hasTheRightValue", test_framework_hasTheRightValue),
        ("test_intentsServiceExtension_hasTheRightValue", test_intentsServiceExtension_hasTheRightValue),
        ("test_messagesApplication_hasTheRightValue", test_messagesApplication_hasTheRightValue),
        ("test_messagesExtension_hasTheRightValue", test_messagesExtension_hasTheRightValue),
        ("test_none_hasTheRightValue", test_none_hasTheRightValue),
        ("test_ocUnitTestBundle_hasTheRightValue", test_ocUnitTestBundle_hasTheRightValue),
        ("test_staticLibrary_hasTheRightValue", test_staticLibrary_hasTheRightValue),
        ("test_stickerPack_hasTheRightValue", test_stickerPack_hasTheRightValue),
        ("test_tvExtension_hasTheRightValue", test_tvExtension_hasTheRightValue),
        ("test_uiTestBundle_hasTheRightValue", test_uiTestBundle_hasTheRightValue),
        ("test_unitTestBundle_hasTheRightValue", test_unitTestBundle_hasTheRightValue),
        ("test_watch2App_hasTheRightValue", test_watch2App_hasTheRightValue),
        ("test_watch2Extension_hasTheRightValue", test_watch2Extension_hasTheRightValue),
        ("test_watchApp_hasTheRightValue", test_watchApp_hasTheRightValue),
        ("test_watchExtension_hasTheRightValue", test_watchExtension_hasTheRightValue),
        ("test_xcodeExtension_hasTheRightValue", test_xcodeExtension_hasTheRightValue),
        ("test_xpcService_hasTheRightValue", test_xpcService_hasTheRightValue),
    ]
}

extension PBXProjEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXProjEncoderTests = [
        ("test_build_phase_headers_sorted", test_build_phase_headers_sorted),
        ("test_build_phase_headers_unsorted", test_build_phase_headers_unsorted),
        ("test_build_phase_resources_sorted", test_build_phase_resources_sorted),
        ("test_build_phase_resources_unsorted", test_build_phase_resources_unsorted),
        ("test_build_phase_sources_sorted", test_build_phase_sources_sorted),
        ("test_build_phase_sources_unsorted", test_build_phase_sources_unsorted),
        ("test_buildFiles_in_default_uuid_order", test_buildFiles_in_default_uuid_order),
        ("test_buildFiles_in_filename_order", test_buildFiles_in_filename_order),
        ("test_file_references_in_default_uuid_order", test_file_references_in_default_uuid_order),
        ("test_file_references_in_filename_order", test_file_references_in_filename_order),
        ("test_navigator_groups_in_default_order", test_navigator_groups_in_default_order),
        ("test_navigator_groups_in_filename_groups_first_order", test_navigator_groups_in_filename_groups_first_order),
        ("test_navigator_groups_in_filename_order", test_navigator_groups_in_filename_order),
        ("test_writeHeaders", test_writeHeaders),
    ]
}

extension PBXProjIntegrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXProjIntegrationTests = [
        ("test_init_initializesTheProjCorrectly", test_init_initializesTheProjCorrectly),
        ("test_write", test_write),
        ("test_write_produces_no_diff", test_write_produces_no_diff),
    ]
}

extension PBXProjObjectsHelpersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXProjObjectsHelpersTests = [
        ("test_targetsNamed_returnsTheCorrectValue", test_targetsNamed_returnsTheCorrectValue),
    ]
}

extension PBXProjectTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXProjectTests = [
        ("test_addLocalSwiftPackage_duplication", test_addLocalSwiftPackage_duplication),
        ("test_addLocalSwiftPackage_throws_frameworksPhaseError", test_addLocalSwiftPackage_throws_frameworksPhaseError),
        ("test_addLocalSwiftPackage", test_addLocalSwiftPackage),
        ("test_addSwiftPackage_duplication", test_addSwiftPackage_duplication),
        ("test_addSwiftPackage", test_addSwiftPackage),
        ("test_attributes", test_attributes),
    ]
}

extension PBXResourcesBuildPhaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXResourcesBuildPhaseTests = [
        ("test_isa_returnsTheCorrectValue", test_isa_returnsTheCorrectValue),
    ]
}

extension PBXRezBuildPhaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXRezBuildPhaseTests = [
        ("test_isa_returnsTheCorrectValue", test_isa_returnsTheCorrectValue),
    ]
}

extension PBXShellScriptBuildPhaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXShellScriptBuildPhaseTests = [
        ("test_returnsTheCorrectIsa", test_returnsTheCorrectIsa),
        ("test_write_showEnvVarsInLog", test_write_showEnvVarsInLog),
    ]
}

extension PBXSourceTreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXSourceTreeTests = [
        ("test_absolute_hasTheCorrectValue", test_absolute_hasTheCorrectValue),
        ("test_buildProductsDir_hasTheCorrectValue", test_buildProductsDir_hasTheCorrectValue),
        ("test_developerDir_hasTheCorrectValue", test_developerDir_hasTheCorrectValue),
        ("test_group_hasTheCorrectValue", test_group_hasTheCorrectValue),
        ("test_none_hasTheCorrectValue", test_none_hasTheCorrectValue),
        ("test_plistReturnsTheRightValue_whenCustom", test_plistReturnsTheRightValue_whenCustom),
        ("test_plistReturnsTheRightValue_whenItsAbsolute", test_plistReturnsTheRightValue_whenItsAbsolute),
        ("test_plistReturnsTheRightValue_whenItsBuildProductsDir", test_plistReturnsTheRightValue_whenItsBuildProductsDir),
        ("test_plistReturnsTheRightValue_whenItsGroup", test_plistReturnsTheRightValue_whenItsGroup),
        ("test_plistReturnsTheRightValue_whenItsNone", test_plistReturnsTheRightValue_whenItsNone),
        ("test_plistReturnsTheRightValue_whenItsSdkRoot", test_plistReturnsTheRightValue_whenItsSdkRoot),
        ("test_plistReturnsTheRightValue_whenItsSourceRoot", test_plistReturnsTheRightValue_whenItsSourceRoot),
        ("test_sdkRoot_hasTheCorrectValue", test_sdkRoot_hasTheCorrectValue),
        ("test_sourceRoot_hasTheCorrectValue", test_sourceRoot_hasTheCorrectValue),
    ]
}

extension PBXSourcesBuildPhaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXSourcesBuildPhaseTests = [
        ("test_itHasTheCorrectIsa", test_itHasTheCorrectIsa),
    ]
}

extension PBXTargetDependencyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXTargetDependencyTests = [
        ("test_hasTheCorrectIsa", test_hasTheCorrectIsa),
    ]
}

extension PBXTargetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXTargetTests = [
        ("test_embedFrameworks_returnsEmpty", test_embedFrameworks_returnsEmpty),
        ("test_embedFrameworks_returnsEmptyIfNoCopyFilesFrameworks", test_embedFrameworks_returnsEmptyIfNoCopyFilesFrameworks),
        ("test_embedFrameworks_returnsTwoBuildPhasesIfCorresponds", test_embedFrameworks_returnsTwoBuildPhasesIfCorresponds),
        ("test_embedFrameworks_returnsUniqueEmbedFrameworksBuildPhase", test_embedFrameworks_returnsUniqueEmbedFrameworksBuildPhase),
        ("test_productNameWithExtension", test_productNameWithExtension),
    ]
}

extension PBXVariantGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PBXVariantGroupTests = [
        ("test_itHasTheCorrectIsa", test_itHasTheCorrectIsa),
    ]
}

extension PathExtrasTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PathExtrasTests = [
        ("testThat_GivenAbsolutePath_WhenRelativeToNotSuperseedingAbsolutePath_ThenResultHasDoubleDot", testThat_GivenAbsolutePath_WhenRelativeToNotSuperseedingAbsolutePath_ThenResultHasDoubleDot),
        ("testThat_GivenAbsoluteSubPath_WhenRelativeToAbsoluteSuperPath_ThenResultIsTheRemainder", testThat_GivenAbsoluteSubPath_WhenRelativeToAbsoluteSuperPath_ThenResultIsTheRemainder),
        ("testThat_GivenAbsoluteSubPath_WhenRelativeToIntersectingAbsolutePath_ThenResultIsTheFullPathToTheRootAndThenFullAbsolutePath", testThat_GivenAbsoluteSubPath_WhenRelativeToIntersectingAbsolutePath_ThenResultIsTheFullPathToTheRootAndThenFullAbsolutePath),
        ("testThat_GivenPath_WhenRelativeToNotSuperseedingPath_ThenResultHasDoubleDot", testThat_GivenPath_WhenRelativeToNotSuperseedingPath_ThenResultHasDoubleDot),
        ("testThat_GivenSubPath_WhenRelativeToSuperPath_ThenResultIsTheRemainder", testThat_GivenSubPath_WhenRelativeToSuperPath_ThenResultIsTheRemainder),
    ]
}

extension ReferenceGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReferenceGeneratorTests = [
        ("test_projectReferencingRemoteXcodeprojBundle_convertsReferencesToPermanent", test_projectReferencingRemoteXcodeprojBundle_convertsReferencesToPermanent),
    ]
}

extension WorkspaceSettingsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WorkspaceSettingsTests = [
        ("test_equals", test_equals),
        ("test_init_when_autoCreateSchemes_is_true", test_init_when_autoCreateSchemes_is_true),
        ("test_init_when_new_build_system", test_init_when_new_build_system),
        ("test_init_when_original_build_system", test_init_when_original_build_system),
        ("test_write", test_write),
    ]
}

extension XCBreakpointListIntegrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCBreakpointListIntegrationTests = [
        ("test_init_initializesTheBreakpointListCorrectly", test_init_initializesTheBreakpointListCorrectly),
        ("test_write", test_write),
    ]
}

extension XCBuildConfigurationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCBuildConfigurationTests = [
        ("test_append_removesDuplicates_when_theSettingIsAnArray", test_append_removesDuplicates_when_theSettingIsAnArray),
        ("test_append_when_duplicateSettingExists", test_append_when_duplicateSettingExists),
        ("test_append_when_theSettingDoesntExist", test_append_when_theSettingDoesntExist),
        ("test_append_when_theSettingExists", test_append_when_theSettingExists),
        ("test_append_when_theSettingExistsAsAnArray", test_append_when_theSettingExistsAsAnArray),
        ("test_initFails_ifNameIsMissing", test_initFails_ifNameIsMissing),
        ("test_isa_hasTheCorrectValue", test_isa_hasTheCorrectValue),
    ]
}

extension XCConfigIntegrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCConfigIntegrationTests = [
        ("test_init_initializesXCConfigWithTheRightProperties", test_init_initializesXCConfigWithTheRightProperties),
        ("test_write_writesTheContentProperly", test_write_writesTheContentProperly),
    ]
}

extension XCConfigTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCConfigTests = [
        ("test_errorDescription_returnsTheCorrectDescription_whenNotFound", test_errorDescription_returnsTheCorrectDescription_whenNotFound),
        ("test_flattened_flattensTheConfigCorrectly", test_flattened_flattensTheConfigCorrectly),
        ("test_init_initializesTheConfigWithTheRightAttributes", test_init_initializesTheConfigWithTheRightAttributes),
        ("test_xcconfig_settingRegex", test_xcconfig_settingRegex),
    ]
}

extension XCConfigurationListTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCConfigurationListTests = [
        ("test_addDefaultConfigurations", test_addDefaultConfigurations),
        ("test_configuration_with_name", test_configuration_with_name),
        ("test_isa_returnsTheCorrectValue", test_isa_returnsTheCorrectValue),
    ]
}

extension XCRemoteSwiftPackageReferenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCRemoteSwiftPackageReferenceTests = [
        ("test_equal", test_equal),
        ("test_init", test_init),
        ("test_name", test_name),
        ("test_plistValues", test_plistValues),
        ("test_versionRequirement_returnsTheRightPlistValues_when_branch", test_versionRequirement_returnsTheRightPlistValues_when_branch),
        ("test_versionRequirement_returnsTheRightPlistValues_when_exact", test_versionRequirement_returnsTheRightPlistValues_when_exact),
        ("test_versionRequirement_returnsTheRightPlistValues_when_range", test_versionRequirement_returnsTheRightPlistValues_when_range),
        ("test_versionRequirement_returnsTheRightPlistValues_when_revision", test_versionRequirement_returnsTheRightPlistValues_when_revision),
        ("test_versionRequirement_returnsTheRightPlistValues_when_upToNextMajorVersion", test_versionRequirement_returnsTheRightPlistValues_when_upToNextMajorVersion),
        ("test_versionRequirement_returnsTheRightPlistValues_when_upToNextMinorVersion", test_versionRequirement_returnsTheRightPlistValues_when_upToNextMinorVersion),
    ]
}

extension XCSchemeIntegrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCSchemeIntegrationTests = [
        ("test_read_iosScheme", test_read_iosScheme),
        ("test_read_minimalScheme", test_read_minimalScheme),
        ("test_testAction_serializingAndDeserializing", test_testAction_serializingAndDeserializing),
        ("test_write_iosScheme", test_write_iosScheme),
        ("test_write_minimalScheme", test_write_minimalScheme),
        ("test_write_testableReferenceAttributesValues", test_write_testableReferenceAttributesValues),
        ("test_write_testableReferenceDefaultAttributesValuesAreOmitted", test_write_testableReferenceDefaultAttributesValuesAreOmitted),
        ("test_write_testPlanReferenceAttributesValues", test_write_testPlanReferenceAttributesValues),
        ("test_write_testPlanReferenceDefaultAttributesValuesAreOmitted", test_write_testPlanReferenceDefaultAttributesValuesAreOmitted),
    ]
}

extension XCSwiftPackageProductDependencyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCSwiftPackageProductDependencyTests = [
        ("test_equal", test_equal),
        ("test_init", test_init),
        ("test_plistValues", test_plistValues),
    ]
}

extension XCWorkspaceDataElementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCWorkspaceDataElementTests = [
        ("test_location_when_file", test_location_when_file),
        ("test_location_when_group", test_location_when_group),
    ]
}

extension XCWorkspaceDataIntegrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCWorkspaceDataIntegrationTests = [
        ("test_init_returnsAllChildren", test_init_returnsAllChildren),
        ("test_init_returnsAllLocationTypes", test_init_returnsAllLocationTypes),
        ("test_init_returnsNestedElements", test_init_returnsNestedElements),
        ("test_init_returnsTheModelWithTheRightProperties", test_init_returnsTheModelWithTheRightProperties),
        ("test_init_throwsIfThePathIsWrong", test_init_throwsIfThePathIsWrong),
        ("test_write", test_write),
    ]
}

extension XCWorkspaceDataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCWorkspaceDataTests = [
        ("test_equal_returnsTheCorrectValue", test_equal_returnsTheCorrectValue),
    ]
}

extension XCWorkspaceIntegrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCWorkspaceIntegrationTests = [
        ("test_init_returnsAWorkspaceWithTheCorrectReference", test_init_returnsAWorkspaceWithTheCorrectReference),
        ("test_initFailsIfThePathIsWrong", test_initFailsIfThePathIsWrong),
        ("test_initTheWorkspaceWithTheRightPropeties", test_initTheWorkspaceWithTheRightPropeties),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AEXML_XcodeFormatTests.__allTests__AEXML_XcodeFormatTests),
        testCase(Array_PlistValueTests.__allTests__Array_PlistValueTests),
        testCase(BuildPhaseTests.__allTests__BuildPhaseTests),
        testCase(BuildSettingProviderTests.__allTests__BuildSettingProviderTests),
        testCase(CommentedStringTests.__allTests__CommentedStringTests),
        testCase(DictionaryExtrasTests.__allTests__DictionaryExtrasTests),
        testCase(Dictionary_PlistValueTests.__allTests__Dictionary_PlistValueTests),
        testCase(ObjectReferenceTests.__allTests__ObjectReferenceTests),
        testCase(PBXAggregateTargetTests.__allTests__PBXAggregateTargetTests),
        testCase(PBXBatchUpdaterTests.__allTests__PBXBatchUpdaterTests),
        testCase(PBXBuildFileTests.__allTests__PBXBuildFileTests),
        testCase(PBXBuildPhaseTests.__allTests__PBXBuildPhaseTests),
        testCase(PBXBuildRuleTests.__allTests__PBXBuildRuleTests),
        testCase(PBXContainerItemProxyTests.__allTests__PBXContainerItemProxyTests),
        testCase(PBXCopyFilesBuildPhaseTests.__allTests__PBXCopyFilesBuildPhaseTests),
        testCase(PBXFileElementTests.__allTests__PBXFileElementTests),
        testCase(PBXFileReferenceTests.__allTests__PBXFileReferenceTests),
        testCase(PBXFrameworksBuildPhaseTests.__allTests__PBXFrameworksBuildPhaseTests),
        testCase(PBXGroupTests.__allTests__PBXGroupTests),
        testCase(PBXHeadersBuildPhaseTests.__allTests__PBXHeadersBuildPhaseTests),
        testCase(PBXNativeTargetTests.__allTests__PBXNativeTargetTests),
        testCase(PBXOutputSettingsTests.__allTests__PBXOutputSettingsTests),
        testCase(PBXProductTypeTests.__allTests__PBXProductTypeTests),
        testCase(PBXProjEncoderTests.__allTests__PBXProjEncoderTests),
        testCase(PBXProjIntegrationTests.__allTests__PBXProjIntegrationTests),
        testCase(PBXProjObjectsHelpersTests.__allTests__PBXProjObjectsHelpersTests),
        testCase(PBXProjectTests.__allTests__PBXProjectTests),
        testCase(PBXResourcesBuildPhaseTests.__allTests__PBXResourcesBuildPhaseTests),
        testCase(PBXRezBuildPhaseTests.__allTests__PBXRezBuildPhaseTests),
        testCase(PBXShellScriptBuildPhaseTests.__allTests__PBXShellScriptBuildPhaseTests),
        testCase(PBXSourceTreeTests.__allTests__PBXSourceTreeTests),
        testCase(PBXSourcesBuildPhaseTests.__allTests__PBXSourcesBuildPhaseTests),
        testCase(PBXTargetDependencyTests.__allTests__PBXTargetDependencyTests),
        testCase(PBXTargetTests.__allTests__PBXTargetTests),
        testCase(PBXVariantGroupTests.__allTests__PBXVariantGroupTests),
        testCase(PathExtrasTests.__allTests__PathExtrasTests),
        testCase(ReferenceGeneratorTests.__allTests__ReferenceGeneratorTests),
        testCase(WorkspaceSettingsTests.__allTests__WorkspaceSettingsTests),
        testCase(XCBreakpointListIntegrationTests.__allTests__XCBreakpointListIntegrationTests),
        testCase(XCBuildConfigurationTests.__allTests__XCBuildConfigurationTests),
        testCase(XCConfigIntegrationTests.__allTests__XCConfigIntegrationTests),
        testCase(XCConfigTests.__allTests__XCConfigTests),
        testCase(XCConfigurationListTests.__allTests__XCConfigurationListTests),
        testCase(XCRemoteSwiftPackageReferenceTests.__allTests__XCRemoteSwiftPackageReferenceTests),
        testCase(XCSchemeIntegrationTests.__allTests__XCSchemeIntegrationTests),
        testCase(XCSwiftPackageProductDependencyTests.__allTests__XCSwiftPackageProductDependencyTests),
        testCase(XCWorkspaceDataElementTests.__allTests__XCWorkspaceDataElementTests),
        testCase(XCWorkspaceDataIntegrationTests.__allTests__XCWorkspaceDataIntegrationTests),
        testCase(XCWorkspaceDataTests.__allTests__XCWorkspaceDataTests),
        testCase(XCWorkspaceIntegrationTests.__allTests__XCWorkspaceIntegrationTests),
    ]
}
#endif
